### ISSUE TITLE
Configuration file parsing fails for inputs "udp://"

### ISSUE THREAD

**Issue by nickpiggottwork** [Opendigitalradio/ODR-DabMux#10]
If I configure a subchannel with
type data|packet|enhancedpacket
and
inputuri "udp://*:12988"
parsing of the address fails with the error:
udp://*:12899: No such file or directory                                                                                                                                                     
udp://*:12899: No such file or directory 

I can't find any syntax for the 'inputuri' directive that will work. I think there's a mismatch in parsing the 'inputuri' directive between the ConfigParser.cpp and the dabInputUdp.cpp.

Nick

**Comment by mpbraendli** [comment]
how does udp://0.0.0.0:12899 behave ?

mpb

**Comment by nickpiggottwork** [comment]
Same error

udp://0.0.0.0:12899: No such file or directory


udp://0.0.0.0:12899: No such file or directory


Nick


On 16 December 2015 at 12:06, Matthias P. Braendli <notifications@github.com
> wrote:

> how does udp://0.0.0.0:12899 behave ?
>
> mpb
>
> On 16. 12. 15 13:03, Nick Piggott wrote:
> > If I configure a subchannel with
> > type data|packet|enhancedpacket
> > and
> > inputuri "udp:///:12988"
> > parsing of the address fails with the error:
> > udp:///:12899: No such file or directory
> >
> > udp://*:12899: No such file or directory
> >
> > I can't find any syntax for the 'inputuri' directive that will work. I
> > think there's a mismatch in parsing the 'inputuri' directive between the
> > ConfigParser.cpp and the dabInputUdp.cpp.
> >
> > Nick
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Opendigitalradio/ODR-DabMux/issues/10>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Opendigitalradio/ODR-DabMux/issues/10#issuecomment-165087163>
> .
>



-- 
Nick

**Comment by mpbraendli** [comment]
"packet" and "enhancedpacket" apparently can only use a FIFO or a file. I'll see if I can get "data" to accept the "udp://" syntax. I don't understand the difference between all these variants yet.

**Comment by mpbraendli** [comment]
Fixed "udp://:12345" syntax for "data" subchannels. I suggest we discuss the needs for packet and enhancedpacket on the mailing-list.
