### ISSUE TITLE
New FIG Carousel scheduler fails at inserting FIG0/3

### ISSUE THREAD

**Issue by nickpiggottwork** [Opendigitalradio/ODR-DabMux#11]
If I enable the new FIG Carousel scheduler, it fails inserting FIG0/3 with the error 'There are too many packet services'.

I have 9 audio services and 1 packet service configured. I have turned on carouseldebug and also have allowed FIG0/3 to go into any FIB by amending line 94 of FIGCarousel.cpp to read

``` load_and_allocate(m_fig0_3, FIBAllocation::FIB_ANY);```

I've added some debug around the allocation of bytes to the FIB, and it seems like FIG0/1 is using 29 bytes, leaving 3 bytes in the FIB. However, I'm not sure why FIG0/3 isn't going into FIB1, or across into the FIB0 in the following frame?

```
Welcome to ODR-DabMux 0.8.1, compiled at Dec 16 2015, 14:25:15

Copyright (C) 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012
Her Majesty the Queen in Right of Canada
(Communications Research Centre Canada) All rights reserved.

Copyright (C) 2013, 2014, 2015 Matthias P. Braendli
http://opendigitalradio.org

Input URLs supported:
 udp fifo file zmq
Inputs format supported:
 raw bridge mpeg packet dmb epm
Output URLs supported:
 file fifo udp tcp simul

ERROR Could not set real-time priority for thread:1
      ODR-DabMux 0.8.1 starting up
ZMQ socket tcp://*:[snip]
[snip]

      --- Multiplex configuration ---
[snip]
      Subchannel   sub-epg
       input
         URI:     ~/site/epgdata
       type:       packet
       id:         10
       bitrate:    8
       protection: EEP 3-A
        option:    0
        level:     2
       SAD:        803
       size (CU):  6
      --- Services list ---
 [snip]
      Service       srv-epg
       label:       EPG
       short label: EPG
       (0xe000)
       id:          0xe1c000d4 (3787456724)
       pty:         0x0 (0)
       language:    0x0 (0)
       announcements: 0x0
       clusters: 
      --- Components list ---
 [snip]
      Component     comp-epg
       service id:             -507510572
       subchannel id:          10
       label:                  
       short label:            
       (0xff00)
       service component type: 0x3c (60)
       (packet) id:            0
       (packet) address:       1
       (packet) app type:      7
       (packet) datagroup:     1
      --- Output list ---
      Output      0
        URI: zmq: tcp://
      Output      1
        URI: simul://
      Start loop
 * 0/0 d:72
 * 0/1 d:76
 * 0/2 d:76
 * 0/3 d:76
 * 0/17 d:176
 * 0/8 d:976
 * 1/0 d:976
 * 0/13 d:976
 * 0/10 d:976
 * 0/9 d:976
 * 1/1 d:976
 * 1/4 d:976
 * 1/5 d:976
 * 0/18 d:976
 * 0/19 d:976
 ****** FIG0/0(special) wrote	6 bytes
 ****** FIG0/1 wrote	0 bytes, complete
 ****** FIG0/2 wrote	0 bytes, complete
*** Filling FIG0/3: remaining=24
*** added header to FIG0/3: remaining=22
*** end of adding component to FIG0/3: remaining=17
 ****** FIG0/3 wrote	7 bytes, complete
 ****** FIG0/17 wrote	0 bytes, complete
 ****** FIG0/8 wrote	0 bytes, complete
 ****** FIG1/0 wrote	0 bytes, incomplete
 ****** FIG0/13 wrote	0 bytes, incomplete
 ****** FIG0/10 wrote	6 bytes, complete
 ****** FIG0/9 wrote	5 bytes, complete
 ****** FIG1/1 wrote	0 bytes, complete
 ****** FIG1/4 wrote	0 bytes, complete
 ****** FIG1/5 wrote	0 bytes, complete
 ****** FIG0/18 wrote	0 bytes, complete
 ****** FIG0/19 wrote	0 bytes, complete
*** Filling FIG0/3: remaining=30
*** added header to FIG0/3: remaining=28
*** end of adding component to FIG0/3: remaining=23
 ****** FIG0/3 wrote	7 bytes, complete
 ****** FIG0/17 wrote	22 bytes, incomplete
 ****** FIG1/0 wrote	0 bytes, incomplete
 ****** FIG0/13 wrote	0 bytes, incomplete
 ****** FIG0/8 wrote	0 bytes, incomplete
 ****** FIG0/10 wrote	0 bytes, incomplete
 ****** FIG0/9 wrote	0 bytes, incomplete
 ****** FIG1/1 wrote	0 bytes, incomplete
 ****** FIG1/4 wrote	0 bytes, incomplete
 ****** FIG1/5 wrote	0 bytes, incomplete
 ****** FIG0/18 wrote	0 bytes, incomplete
 ****** FIG0/19 wrote	0 bytes, complete
*** Filling FIG0/3: remaining=30
*** added header to FIG0/3: remaining=28
*** end of adding component to FIG0/3: remaining=23
 ****** FIG0/3 wrote	7 bytes, complete
 ****** FIG0/17 wrote	22 bytes, incomplete
 ****** FIG1/0 wrote	0 bytes, incomplete
 ****** FIG0/13 wrote	0 bytes, incomplete
 ****** FIG0/8 wrote	0 bytes, incomplete
 ****** FIG0/10 wrote	0 bytes, incomplete
 ****** FIG0/9 wrote	0 bytes, incomplete
 ****** FIG1/1 wrote	0 bytes, incomplete
 ****** FIG1/4 wrote	0 bytes, incomplete
 ****** FIG1/5 wrote	0 bytes, incomplete
 ****** FIG0/18 wrote	0 bytes, incomplete
 ****** FIG0/19 wrote	0 bytes, complete
 * 0/0 d:72
 * 0/1 d:76
 * 0/2 d:76
 * 0/3 d:76
 * 0/17 d:176
 * 0/8 d:976
 * 1/0 d:952
 * 0/13 d:952
 * 0/10 d:976
 * 0/9 d:976
 * 1/1 d:976
 * 1/4 d:976
 * 1/5 d:976
 * 0/18 d:976
 * 0/19 d:976
 ****** FIG0/1 wrote	29 bytes, incomplete
 ****** FIG0/2 wrote	0 bytes, incomplete
*** Filling FIG0/3: remaining=1
*** added header to FIG0/3: remaining=18446744073709551615
*** end of adding component to FIG0/3: remaining=18446744073709551610
ERROR can't add FIG 0/3 to FIB, too many packet services
WARN  RC: Leaving
ERROR Multiplex initialisation aborted: ODR-DabMux initialisation error
      exiting...
      ...done
```

**Comment by mpbraendli** [comment]
The FIG0/3 generator is missing an internal mini-carousel that goes
through the components. I had this as a task for some time, but I didn't
expect it to become important that quickly. I will give this higher
priority.

Other FIGs have this internal carousel, e.g. FIG0/8. The m_initialised
flag and the componentFIG0_8 iterator are used for that. The fill()
function then goes through the components in order, and stops before it
overfills the FIB. That is what is missing for the FIG0/3. The
complete_fig_transmitted flag and the num_bytes_written have also to be
set accordingly. That should be enough.

Do you want to take care of this ?

mpb

**Comment by nickpiggottwork** [comment]
Hi,

Yes, I can see the relevant code in FIG0/8. Unfortunately, I'm far from
being a C++ coder, and I think it's more likely I'll get it wrong than
right if I try and re-implement the mini-carousel in FIG0/3.

Sorry!

On 16 December 2015 at 14:45, Matthias P. Braendli <notifications@github.com
> wrote:

> The FIG0/3 generator is missing an internal mini-carousel that goes
> through the components. I had this as a task for some time, but I didn't
> expect it to become important that quickly. I will give this higher
> priority.
>
> Other FIGs have this internal carousel, e.g. FIG0/8. The m_initialised
> flag and the componentFIG0_8 iterator are used for that. The fill()
> function then goes through the components in order, and stops before it
> overfills the FIB. That is what is missing for the FIG0/3. The
> complete_fig_transmitted flag and the num_bytes_written have also to be
> set accordingly. That should be enough.
>
> Do you want to take care of this ?
>
> mpb
>
> On 16. 12. 15 15:36, Nick Piggott wrote:
> > If I enable the new FIG Carousel scheduler, it fails inserting FIG0/3
> > with the error 'There are too many packet services'.
> >
> > I have 9 audio services and 1 packet service configured. I have turned
> > on carouseldebug and also have allowed FIG0/3 to go into any FIB by
> > amending line 94 of FIGCarousel.cpp to read
> >
> > load_and_allocate(m_fig0_3, FIBAllocation::FIB_ANY);
> >
> > I've added some debug around the allocation of bytes to the FIB, and it
> > seems like FIG0/1 is using 29 bytes, leaving 3 bytes in the FIB.
> > However, I'm not sure why FIG0/3 isn't going into FIB1, or across into
> > the FIB0 in the following frame?
> >
> > new_carousel_fig03_debug.txt
> > <
> https://github.com/Opendigitalradio/ODR-DabMux/files/64100/new_carousel_fig03_debug.txt
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Opendigitalradio/ODR-DabMux/issues/11>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Opendigitalradio/ODR-DabMux/issues/11#issuecomment-165130075>
> .
>



-- 
Nick

**Comment by mpbraendli** [comment]
Okay, I will look into this soon.

Can you give me a config file that currently fails ? Then I can test.

mpb

**Comment by nickpiggottwork** [comment]
Have shared with you privately, as it's got some details on ports and so on.

**Comment by mpbraendli** [comment]
7be6121103ed6e0c9b631a0eb3cc0b120ee4a08d fixes this.
