### ISSUE TITLE
Multiplexing on Raspberry Pi, how does it air?

### ISSUE THREAD

**Issue by danielmoore123** [Opendigitalradio/ODR-DabMux#13]
Hi There,
Newby here, just wondering how after multiplexing an MP2 signal from stream how to air this for tuning into a DAB Digital Radio. I am wanting DAB here and not DAB+.
Many Thanks

**Comment by danielmoore123** [comment]
Can this be aired from a GPO Pin, for example that of a Raspberry Pi?

**Comment by mpbraendli** [comment]
No, a GPIO is not good enough. You need to modulate the multiplex at some point.

Please read the guide, it explains the big picture better:
http://opendigitalradio.github.io/mmbtools-doc/mmbtools.pdf
