### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by danielmoore123** [Opendigitalradio/ODR-DabMux#14]
Hi, I am following http://wiki.opendigitalradio.org/ODR-DabMux and get this error:
-bash: odr-dabmux: command not found
I get the same for ./bootstrap despite ./configure working ok?
Any ideas? I'm stuck and followed this step-by-step.
Regards

**Comment by mpbraendli** [comment]
I don't understand what you are doing exactly. Please describe more in detail.

**Comment by danielmoore123** [comment]
I'm following that guide that's attached. When I get to the Compilation stage, I get this error.

**Comment by mpbraendli** [comment]
can you please copy-paste your commands and the respective output?
