### ISSUE TITLE
DAB recipes to install Opendigitalradio and related tools

### ISSUE THREAD

**Issue by DavidLutton** [Opendigitalradio/ODR-DabMux#15]
I have made [DAB recipes](https://github.com/DavidLutton/DAB-recipes) to install [Opendigitalradio](https://github.com/Opendigitalradio) and related tools with [PyBOMBS (Python Build Overlay Managed Bundle System)](https://github.com/gnuradio/pybombs).

PyBOMBS (Python Build Overlay Managed Bundle System) compiles UHD and rtl-sdr into a prefix which is convenient for [Opendigitalradio](https://github.com/Opendigitalradio) and [dabtools](https://github.com/linuxstb/dabtools) when PyBOMBS is used to build into the same prefix.

Anyone willing to change their build recommendations?
Any other comments?

**Comment by mpbraendli** [comment]
This is quite cool! I've never used PyBOMBS, but if it's as easy as your INSTALL.md suggests then I'm in favour of communicating this as a way of installing the tools!
Are you willing to take care of the maintenance of these?
About the data repositories: they're not yet in a state ready for widespread usage, but hopefully soon!
If you agree, I will mention this on our website. Would you prefer keeping this under your name, or would be agree moving it into the github organisation? (I'll add you to the organisation of course)

**Comment by mpbraendli** [comment]
I've updated http://www.opendigitalradio.org/mmbtools

**Comment by DavidLutton** [comment]
Cool

I am willing to be the maintainer of this
I agree to move it into the organisation and to be added to the organisation

**Comment by mpbraendli** [comment]
Great, thanks a lot!

I've added you to the organisation. I'll let you transfer the repo. If there is any trouble with the access rights let me know.

**Comment by DavidLutton** [comment]
Github:"You don’t have admin rights to Opendigitalradio"
In order to create/move a repo into Opendigitalradio

**Comment by DavidLutton** [comment]
I know would be a matter of trust for giving admin to the organisation.
Would you prefer me to transfer the repo to @mpbraendli then you can move it into the organisation

**Comment by mpbraendli** [comment]
Ehm, ok, except that it seems I don't have persmission to move your repo :-P

**Comment by mpbraendli** [comment]
Ok try again it should be possible for you to create a repo now
