### ISSUE TITLE
No error message when inputfile port are already used.

### ISSUE THREAD

**Issue by YoannQueret** [Opendigitalradio/ODR-DabMux#21]
If inputfile port are already used by another program, ODR-DabMux start but do nothing without any error message.

**Comment by mpbraendli** [comment]
Cannot reproduce.
When I start ODR-DabMux with a ZeroMQ input that should listen on a port that is already used on my system, it aborts with

    ERROR Caught runtime error : ZMQ bind for input sub-fb failedAddress already in use

Is that your scenario?

**Comment by YoannQueret** [comment]
I can reproduce with a specific context :
- odr-dabmux with an stdout output in a fifo file
- odr-dabmod not loaded (don't read the the fifo file).

When the fifo file is read, i have the correct message :
`ERROR Caught runtime error : ZMQ bind for input sub_radio2 failedAddress already in use
      exiting...`

**Comment by mpbraendli** [comment]
Ah ok, it's because odr-dabmux is waiting for the fifo before it prints and handles that error. Now it's clear to me.

**Comment by mpbraendli** [comment]
Not sure if I'm going to fix this, it would need some internal reorganisation, and it's going to fail with an error message once the consumer (i.e. ODR-DabMod) starts reading from the fifo.
