### ISSUE TITLE
dabOutput/dabOutput.h:301:29: error: call to ‘zmq::context_t::context_t(int, int)

### ISSUE THREAD

**Issue by stackprogramer** [Opendigitalradio/ODR-DabMux#22]
Hi,when i want to install your source on Debian jessie,it returns errors:
it can not compile on new os linux,any idea, thanks 
best regards stackprogramer

> mq.hpp:565:22: error: ‘ZMQ_EVENT_DISCONNECTED’ was not declared in this scope
                 case ZMQ_EVENT_DISCONNECTED:
                      ^
In file included from ./input/inputs.h:33:0,
                 from input/Prbs.h:33,
                 from DabMux.cpp:97:
./RemoteControl.h: In constructor ‘RemoteControllerZmq::RemoteControllerZmq()’:
./RemoteControl.h:273:26: error: call to ‘zmq::context_t::context_t(int, int)’ uses the default argument for parameter 2, which is not yet defined
             m_endpoint("") { }
                          ^
./RemoteControl.h: In constructor ‘RemoteControllerZmq::RemoteControllerZmq(const string&)’:
./RemoteControl.h:279:63: error: call to ‘zmq::context_t::context_t(int, int)’ uses the default argument for parameter 2, which is not yet defined
             m_child_thread(&RemoteControllerZmq::process, this) { }
                                                               ^
In file included from DabMux.cpp:98:0:
input/Zmq.h: In constructor ‘Inputs::ZmqBase::ZmqBase(std::string, Inputs::dab_input_zmq_config_t)’:
input/Zmq.h:160:49: error: call to ‘zmq::context_t::context_t(int, int)’ uses the default argument for parameter 2, which is not yet defined
             m_prebuf_current(config.prebuffering) {
                                                 ^
In file included from DabMux.cpp:100:0:
dabOutput/dabOutput.h: In constructor ‘DabOutputZMQ::DabOutputZMQ(const string&)’:
dabOutput/dabOutput.h:301:29: error: call to ‘zmq::context_t::context_t(int, int)’ uses the default argument for parameter 2, which is not yet defined
             zmq_message_ix(0)
                             ^
Makefile:851: recipe for target 'odr_dabmux-DabMux.o' failed
make[2]: *** [odr_dabmux-DabMux.o] Error 1
make[2]: Leaving directory '/home/sp/Downloads/ODR-DabMux-master/src'
Makefile:399: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/sp/Downloads/ODR-DabMux-master'
Makefile:339: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by basicmaster** [comment]
Hmm, which version of libzmq do you have installed?

**Comment by mpbraendli** [comment]
@stackprogramer any updates?

**Comment by stackprogramer** [comment]
@mpbraendli thanks you i soon will test update commit and share result here
