### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mspanc** [Opendigitalradio/ODR-DabMux#23]
I am using odr-dabmux 1.2.1 on ubuntu 16.04.

I am using `./configure --enable-output-raw` configure command an FarSync output.

It seems it has a small memory leak:

![memory-day](https://cloud.githubusercontent.com/assets/389651/26559714/abcce7ac-44b1-11e7-8ad3-fb6044ef1946.png)

The moment when memory usage went down was when I restarted it.

It's hard for me to grab valgrind trace as it is happening on production, but I'll try.

**Comment by mpbraendli** [comment]
We're running a site with a Farsync in production with v0.7.5 and we don't see a memory leak, but it could have been introduced later. What are you running?

**Comment by YoannQueret** [comment]
odr-DabMux running in production with v1.2.1 and ETI output with Farsync card in Paris without this memory leak. Running on debian Jessie, not Ubuntu.

**Comment by mpbraendli** [comment]
@mspanc Hi Marcin, any news?

**Comment by mspanc** [comment]
Nope, I was busy with other things, but I have to do some upgrade to our DAB multiplexer soon anyway so I'll try to look at this.

**Comment by mpbraendli** [comment]
Hi,
Is this still an issue?

**Comment by mspanc** [comment]
I was on long vacations, and just came back, I'll check that out and let you know.

**Comment by mpbraendli** [comment]
Hi @mspanc 
please open again if it's still an issue.
