### ISSUE TITLE
Add possibility to control FIG 0/13

### ISSUE THREAD

**Issue by coinchon** [Opendigitalradio/ODR-DabMux#3]
In the current version, the mux sends FIG 0/13 signalling slideshow for every service, whether they have slideshow service or not.

It should be possible to control this per channel to avoid signalling slideshow in FIG 0/13 on service that don't have it. In particular, this is problematic for receivers that supports RadioDNS/RadioVIS as they will then prioritize slideshow over RadioVIS and so won't display RadioVIS if the slideshow signalling is present.

**Comment by mpbraendli** [comment]
Commit 9164c7e adds the ability to set this in the configuration file. Can you please test this ?

**Comment by nickpiggottwork** [comment]
Works for me.

**Comment by mpbraendli** [comment]
I should probably go through the open issues... :-D
