### ISSUE TITLE
How to use DabMux as T-DMB multiplexer mux configuration file?

### ISSUE THREAD

**Issue by CodeMadeByMw** [Opendigitalradio/ODR-DabMux#30]
Hello！

I have consulted the source code of DABMux, which includes DMB code. I want to use DABMux as a multiplexer of T-DMB. I am wondering if you could kindly tell me how to configure the related parameters in the configuration file of mux.

Please contact me with the email ''1257452084@qq.com''.

**Comment by mpbraendli** [comment]
Hi,
There is indeed some code in ODR-DabMux for DMB multiplexing, but it is not currently functional. I would welcome patches that allow ODR-DabMux to be used for T-DMB, but I'm not able to develop this myself.
