### ISSUE TITLE
recompile with -fPIC

### ISSUE THREAD

**Issue by maceyldn** [Opendigitalradio/ODR-DabMux#31]
Hi,

Appear to have a problem compiling latest release.

root@zippy:~/ODR-DabMux# make
make  all-am
make[1]: Entering directory '/root/ODR-DabMux'
  CXXLD    odr-dabmux
/usr/bin/ld: src/odr_dabmux-crc.o: relocation R_X86_64_32S against symbol `crc8tab' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: src/odr_dabmux-mpeg.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:915: recipe for target 'odr-dabmux' failed
make[1]: *** [odr-dabmux] Error 1
make[1]: Leaving directory '/root/ODR-DabMux'
Makefile:650: recipe for target 'all' failed
make: *** [all] Error 2

Great Product.
Any Suggestions?

Thanks
Andy

**Comment by maceyldn** [comment]
Dunno if this is just my environment... but fixed by changing the lines in Makefile.am

odr_dabmux_CFLAGS   =-Wall -fPIC $(INCLUDE) $(GITVERSION_FLAGS)
odr_dabmux_CXXFLAGS =-Wall -fPIC -std=c++11 $(INCLUDE) $(GITVERSION_FLAGS) $(BOOST_CPPFLAGS) $(ZMQ_CPPFLAGS)
o

odr_zmq2farsync_CFLAGS   = -Wall -fPIC $(ZMQ_CPPFLAGS) $(GITVERSION_FLAGS) $(INCLUDE)
odr_zmq2farsync_CXXFLAGS = -Wall -fPIC -std=c++11 $(ZMQ_CPPFLAGS) $(GITVERSION_FLAGS) $(INCLUDE)

odr_zmq2edi_CFLAGS   = -Wall -fPIC $(ZMQ_CPPFLAGS) $(GITVERSION_FLAGS) $(INCLUDE)
odr_zmq2edi_CXXFLAGS = -Wall -fPIC -std=c++11 $(ZMQ_CPPFLAGS) $(GITVERSION_FLAGS) $(INCLUDE)

Happy to do a PR if this effects everyones.

Andy

**Comment by mpbraendli** [comment]
Hi @maceyldn 
What distribution are you running? What compiler version?
Do you override CFLAGS or CXXFLAGS in your env? What's the output of `env` ?

I would like to avoid setting `-fPIC`, this should be the user's or packager's decision, not mine.
Cheers
mpb

**Comment by mpbraendli** [comment]
Please reopen if still a problem.
