### ISSUE TITLE
Boost version error on Buildroot

### ISSUE THREAD

**Issue by janblaesi** [Opendigitalradio/ODR-DabMux#33]
Hello there,

when compiling ODR-DabMux using Buildroot and a Linaro Cross-compile toolchain I get the following error:

```
checking for PTHREAD_PRIO_INHERIT... yes
checking for boostlib >= 1.48.0 (104800)... yes
checking whether the Boost::Thread library is available... yes
configure: error: Could not find a version of the library!
```

I tried configuring with ```--with-boost-libdir=/usr/lib/arm-linux-gnueabihf``` but it didn't help, it seems like the boost libraries are not there but under /usr/lib, providing that path to said command line switch yields the error above again.

Boost version is 1.66

Greetings,
Jan

**Comment by mpbraendli** [comment]
Hi Jan,
can you give me the `config.log` after the failing `./configure` ? Maybe in a github gist or in a pastebin.
Cheers

**Comment by janblaesi** [comment]
Sure thing:
https://gist.github.com/janblaesi/7bc37c4b02a257e9fae3ad6d54629448

**Comment by mpbraendli** [comment]
Mmmh well, that was less helpful than I had hoped... Can you also give me the `configure` script that was generated?

**Comment by janblaesi** [comment]
That would be this one:
https://gist.github.com/janblaesi/f5f81767790a31e3be2e1581a3a4fa86

**Comment by mpbraendli** [comment]
I'm a bit at a loss. Do you have the correct `boost_thread.so` in that library folder?

**Comment by janblaesi** [comment]
![image](https://user-images.githubusercontent.com/44644172/47797298-5a671180-dd26-11e8-84d5-3cf6bebd7bfd.png)

I have this one

**Comment by mpbraendli** [comment]
Oh there's a `-mt` and a non `-mt`, I wonder if that makes a difference. I looked that up in the past but forgot why that existed. I won't have time to look into today though.

**Comment by janblaesi** [comment]
In Buildroot I can select the build model for boost, when I select system, i get the following:
![screenshot_2](https://user-images.githubusercontent.com/44644172/47798703-335e0f00-dd29-11e8-81bd-109a86f7ce31.png)
When I select Tagged, i get this:
![screenshot_1](https://user-images.githubusercontent.com/44644172/47798732-3a851d00-dd29-11e8-9a05-44e1dfcd57bb.png)
And finally, when I select versioned I get this:
![image](https://user-images.githubusercontent.com/44644172/47799017-b8492880-dd29-11e8-8a71-3d44a20199b7.png)

So the 3 different types of file in the first screenshot are a result of me running the two build models after each other without cleaning, but even doing that DabMux will not build.

**Comment by mpbraendli** [comment]
Ok I understand. Have you tried giving a path to the  `--with-boost-thread` option?

Maybe you'll need to do it for boost-system and boost-asio too.

I saw that `--with-boost` also accepts a path, not sure if that is useful.

Seen on: http://www.randspringer.de/boost/ucl-sbs.html

**Comment by janblaesi** [comment]
Just tried that, it works now!
Thank you very much!

Greetings,
Jan

**Comment by mpbraendli** [comment]
Thanks for the info.

Out of curiosity, where are you going to use that system built with buildroot? I'm always interested in hearing how users implement the mmbTools.

**Comment by andimik** [comment]
@mpbraendli 

Could you fix that for Raspberry Pi?

I still have to use

``` 
./configure --with-boost-libdir=/usr/lib/arm-linux-gnueabihf
```
Seems you need to change the code in `configure` file lines 5089ff as a Raspberry is arm, not x86_64.

Or should I send you a PR with a remark in `INSTALL.md`?

**Comment by mpbraendli** [comment]
I'll put a mention in INSTALL.md as that's probably best.

Keep in mind `configure` is a generated file, see https://autotools.io/ if you want to learn more about the autotools.
