### ISSUE TITLE
Command "values" append "Invalid command" to json result

### ISSUE THREAD

**Issue by YoannQueret** [Opendigitalradio/ODR-DabMux#4]
{ "values" : {
 "sub_radio1" : { "inputstat" : {"min_fill": 20160, "max_fill": 22752, "peak_left": -1, "peak_right": -1, "num_underruns": 49, "num_overruns": 386 } } ,
 "sub_radio2" : { "inputstat" : {"min_fill": 5184, "max_fill": 10656, "peak_left": 0, "peak_right": 0, "num_underruns": 48, "num_overruns": 386 } } ,
 "sub_radio3" : { "inputstat" : {"min_fill": 4320, "max_fill": 10368, "peak_left": -1, "peak_right": -1, "num_underruns": 47, "num_overruns": 386 } } ,
 "sub_radio4" : { "inputstat" : {"min_fill": 18432, "max_fill": 21600, "peak_left": -5, "peak_right": -5, "num_underruns": 47, "num_overruns": 386 } }}
}
Invalid command

Missing "else" before "if" on line 280 in ManagementServer.cpp file ?

**Comment by mpbraendli** [comment]
Yes. Fixed.
Thank you !
