### ISSUE TITLE
Compiling it on Mingw64 Msys2

### ISSUE THREAD

**Issue by veso266** [Opendigitalradio/ODR-DabMux#40]
Hi there
I am trying to build ODR-DabMux on windows with Mingw (msys2)

after building ZeroMQ per instructions:https://github.com/zeromq/libzmq/blob/master/INSTALL
 and copying lib into /migw64/lib, include into /mingw64/include
and Boost per this instructions: https://gist.github.com/zrsmithson/0b72e0cb58d0cb946fc48b5c88511da8

and then trying to build with
```sh
./autogen.sh
./configure  --with-boost-libdir=/usr/lib #I installed boost into /usr/lib
```
I was almost able to build this but then syslog failed
```
src/Log.h:34:10: fatal error: syslog.h: No such file or directory
 #include <syslog.h>
```
apparently windows doesn't have syslog(3) functions so I was wondering is there any other logger I could pipe errors to or some other workaround I could use on windows?

Thanks for Anwsering and Best Regards

**Comment by mpbraendli** [comment]
Hi!
I'm not aware of a syslog implementation on cygwin, however it should be relatively easy to add a `configure` check for syslog availability, and then not compile the syslog output. (using a preprocessor define)
There is a console output that can be used in any case.
Let me know if you do something in that direction!
Cheers

**Comment by veso266** [comment]
Well just define empty methods on windows: https://doxygen.openinfosecfoundation.org/win32-syslog_8h_source.html

maybe someday try to use this instead on windows: https://github.com/asankah/syslog-win32

**Comment by veso266** [comment]
OK after defining empty syslog macros: https://doxygen.openinfosecfoundation.org/win32-syslog_8h_source.html

 I was able to make syslog error go away

```c++
#ifdef __MINGW32__
	#include "win32-syslog.h"
#else
	#include <syslog.h>
#endif
```

but now I have problems with sockets
according to this: https://stackoverflow.com/a/4642169/3368585
there is no socket.h and netinet/in.h on windows there is winsock

can I just disable network for now, exept zeroMQ is it crucial?

Thanks for Anwsering and Best Regards
BTW: maybe you could reopne that issue

**Comment by MaPePeR** [comment]
Maybe you could put your changes to make it work in a pull request, so it can be easily integrated.

**Comment by veso266** [comment]
Yea
The problem is i am fighting with sockets now
But if I ever make it workable there will be a pull requst :)
