### ISSUE TITLE
zmqinput-keygen return key generation failed

### ISSUE THREAD

**Issue by YoannQueret** [Opendigitalradio/ODR-DabMux#5]
With zeromq-4.0.4 zmqinput-keygen return "key generation failed" but two files (pub & sec) are created. I have not tested if file are correct.

$ zmqinput-keygen mykey
key generation failed

$ cat mykey.pub
.N=��@����pCU+��!��e

$ cat mykey.sec
pCU+��
@

**Comment by mpbraendli** [comment]
You are probably missing libsodium, which offers the crypto features used in zeromq.
But it was an error to write the two files in this case. This has been fixed: no files are written if the key generation fails.
