### ISSUE TITLE
FIG 0/14 not transmitted for Enhanced Packet Mode subchannels

### ISSUE THREAD

**Issue by nickpiggott** [Opendigitalradio/ODR-DabMux#55]
If a subchannel is configured as "enhancedpacket", then a corresponding FIG 0/14 entry should be signalled (EN 300 401 v2.1.1 section 6.2.2).

The purpose of FIG0/14 is signal the scheme of FEC being applied to the subchannel. It is an 8 bit field - b7-b2  represent the SubChannelD, and b1-b0 bits representing the FEC scheme. The currently only applicable value for the scheme type (b1-b0) is "01" (decimal 1).

It doesn't look like FIG0/14 is being transmitted when a subchannel is configured as "enhancedpacket".

![image](https://user-images.githubusercontent.com/11558362/156233947-ea1cdaa6-15ae-4715-8555-f842afb0ed55.png)

**Comment by mpbraendli** [comment]
Yep, that's indeed not implemented...

**Comment by nickpiggott** [comment]
Have attempted to add it, and created a Pull Request for it. Be gentle with me.
