### ISSUE TITLE
odr-dab-mux to easydab v2 card - connection optimization

### ISSUE THREAD

**Issue by chicco64** [Opendigitalradio/ODR-DabMux#56]
Hi !
I would like to understand if it is possible to optimize the connection between odr-dab-mux (currently virtualized in the datacenter) and the easydab v2 card.
I am currently connected via ZeroMQ (latency 55ms) but I often find disconnections, I think due to insufficient buffer of the easydab v2 card.
Do you think it's possible? thank you

**Comment by mpbraendli** [comment]
Hi, since this is not only related to ODR-DabMux, please ask on the discussion group https://groups.io/g/odr-mmbtools There are more users with EasyDABv2 there!
