### ISSUE TITLE
url for package repository in install.md is wrong

### ISSUE THREAD

**Issue by allegfede** [Opendigitalradio/ODR-DabMux#67]
hello,
in install.md first pass the url is wrong:
curl -fsSL http://debian.opendigitalradio.org/odr.asc | sudo tee /etc/apt/trusted.gpg.d/odr.asc 1>/dev/null

the file is now named:
https://debian.opendigitalradio.org/opendigitalradio.asc

also:
curl -fsSL http://debian.opendigitalradio.org/odr.list | sudo tee /etc/apt/sources.list.d/odr.list 1>/dev/null

do not exists

**Comment by colisee** [comment]
Ciao @allegfede,

you are totally right! I forgot to update the file install.md when I changed our Debian repository. I will also check if we have the same issue on odr-audioenc, odr-padenc and odr-dabmod. 

I’ll take care of it. 

Grazie.

**Comment by allegfede** [comment]
Thanks.

Il sab 2 set 2023, 15:46 Robin ALEXANDER ***@***.***> ha
scritto:

**Comment by mpbraendli** [comment]
This is fixed in `next`
