### ISSUE TITLE
Error during make with --enable-input-test

### ISSUE THREAD

**Issue by YoannQueret** [Opendigitalradio/ODR-DabMux#8]
Error during make with  --enable-input-test configure option

[...]
  CXX      fig/odr_dabmux-FIGCarousel.o
ConfigParser.cpp: In function ‘void setup_subchannel_from_ptree(dabSubchannel*, boost::property_tree::ptree&, boost::shared_ptr<dabEnsemble>, std::string, boost::shared_ptr<BaseRemoteController>)’:
ConfigParser.cpp:781:25: error: ‘DataDmb’ was not declared in this scope
         subchan->type = DataDmb;
                         ^
  CC       odr_bridgetest-bridge.o
  CC       odr_bridgetest-crc.o
  CXX      zmq2farsync/odr_zmq2farsync-zmq2farsync.o
Makefile:1344: recipe for target 'odr_dabmux-ConfigParser.o' failed
make[2]: *** [odr_dabmux-ConfigParser.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/usr/src/ODR-DabMux/src'
Makefile:399: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/ODR-DabMux'
Makefile:339: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mpbraendli** [comment]
Merci, résolu.
